services:
  db:
    image: postgres:15-alpine
    container_name: my_postgres_database
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: super_password
      POSTGRES_DB: my_project_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: my_backend_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin_user
      - DB_PASSWORD=super_password
      - DB_NAME=my_project_db
    depends_on:
      - db

volumes:
  postgres_data: